// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.lipalightninglib;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the detils of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.ptr.ByReference
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.locks.ReentrantLock
import kotlin.concurrent.withLock

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : RustBuffer(), Structure.ByValue
    class ByReference : RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipalightninglib_7771_rustbuffer_alloc(size, status).also {
                if(it.data == null) {
                   throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
               }
            }
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipalightninglib_7771_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Int = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    fun isSuccess(): Boolean {
        return code == 0
    }

    fun isError(): Boolean {
        return code == 1
    }

    fun isPanic(): Boolean {
        return code == 2
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    if (status.isSuccess()) {
        return return_value
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_lipalightninglib"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "lipalightninglib")
            .also { lib: _UniFFILib ->
                FfiConverterTypeEventsCallback.register(lib)
                }
            
        }
    }

    fun ffi_lipalightninglib_7771_LightningNode_object_free(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_LightningNode_new(`config`: RustBuffer.ByValue,`eventsCallback`: Long,
    _uniffi_out_err: RustCallStatus
    ): Pointer

    fun lipalightninglib_7771_LightningNode_get_node_info(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_query_lsp_fee(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_calculate_lsp_fee(`ptr`: Pointer,`amountMsat`: Long,
    _uniffi_out_err: RustCallStatus
    ): Long

    fun lipalightninglib_7771_LightningNode_create_invoice(`ptr`: Pointer,`amountMsat`: Long,`description`: RustBuffer.ByValue,`metadata`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_decode_invoice(`ptr`: Pointer,`invoice`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_pay_invoice(`ptr`: Pointer,`invoice`: RustBuffer.ByValue,`metadata`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_LightningNode_get_latest_payments(`ptr`: Pointer,`numberOfPayments`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_get_payment(`ptr`: Pointer,`hash`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_foreground(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_LightningNode_background(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_LightningNode_list_currency_codes(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_get_exchange_rates(`ptr`: Pointer,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_LightningNode_change_fiat_currency(`ptr`: Pointer,`fiatCurrency`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_LightningNode_change_timezone_config(`ptr`: Pointer,`timezoneConfig`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun ffi_lipalightninglib_7771_EventsCallback_init_callback(`callbackStub`: ForeignCallback,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_init_native_logger_once(`minLevel`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun lipalightninglib_7771_generate_secret(`passphrase`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_mnemonic_to_secret(`mnemonicString`: RustBuffer.ByValue,`passphrase`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun lipalightninglib_7771_words_by_prefix(`prefix`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_lipalightninglib_7771_rustbuffer_alloc(`size`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_lipalightninglib_7771_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_lipalightninglib_7771_rustbuffer_free(`buf`: RustBuffer.ByValue,
    _uniffi_out_err: RustCallStatus
    ): Unit

    fun ffi_lipalightninglib_7771_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,
    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    
}

// Public interface members begin here.


public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteArr.size)
        rbuf.asByteBuffer()!!.put(byteArr)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        buf.putInt(byteArr.size)
        buf.put(byteArr)
    }
}


public object FfiConverterTimestamp: FfiConverterRustBuffer<java.time.Instant> {
    override fun read(buf: ByteBuffer): java.time.Instant {
        val seconds = buf.getLong()
        // Type mismatch (should be u32) but we check for overflow/underflow below
        val nanoseconds = buf.getInt().toLong()
        if (nanoseconds < 0) {
            throw java.time.DateTimeException("Instant nanoseconds exceed minimum or maximum supported by uniffi")
        }
        if (seconds >= 0) {
            return java.time.Instant.EPOCH.plus(java.time.Duration.ofSeconds(seconds, nanoseconds))
        } else {
            return java.time.Instant.EPOCH.minus(java.time.Duration.ofSeconds(-seconds, nanoseconds))
        }
    }

    // 8 bytes for seconds, 4 bytes for nanoseconds
    override fun allocationSize(value: java.time.Instant) = 12

    override fun write(value: java.time.Instant, buf: ByteBuffer) {
        var epochOffset = java.time.Duration.between(java.time.Instant.EPOCH, value)

        var sign = 1
        if (epochOffset.isNegative()) {
            sign = -1
            epochOffset = epochOffset.negated()
        }

        if (epochOffset.nano < 0) {
            // Java docs provide guarantee that nano will always be positive, so this should be impossible
            // See: https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html
            throw IllegalArgumentException("Invalid timestamp, nano value must be non-negative")
        }

        buf.putLong(sign * epochOffset.seconds)
        // Type mismatch (should be u32) but since values will always be between 0 and 999,999,999 it should be OK
        buf.putInt(epochOffset.nano)
    }
}


public object FfiConverterDuration: FfiConverterRustBuffer<java.time.Duration> {
    override fun read(buf: ByteBuffer): java.time.Duration {
        // Type mismatch (should be u64) but we check for overflow/underflow below
        val seconds = buf.getLong()
        // Type mismatch (should be u32) but we check for overflow/underflow below
        val nanoseconds = buf.getInt().toLong()
        if (seconds < 0) {
            throw java.time.DateTimeException("Duration exceeds minimum or maximum value supported by uniffi")
        }
        if (nanoseconds < 0) {
            throw java.time.DateTimeException("Duration nanoseconds exceed minimum or maximum supported by uniffi")
        }
        return java.time.Duration.ofSeconds(seconds, nanoseconds)
    }

    // 8 bytes for seconds, 4 bytes for nanoseconds
    override fun allocationSize(value: java.time.Duration) = 12

    override fun write(value: java.time.Duration, buf: ByteBuffer) {
        if (value.seconds < 0) {
            // Rust does not support negative Durations
            throw IllegalArgumentException("Invalid duration, must be non-negative")
        }

        if (value.nano < 0) {
            // Java docs provide guarantee that nano will always be positive, so this should be impossible
            // See: https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html
            throw IllegalArgumentException("Invalid duration, nano value must be non-negative")
        }

        // Type mismatch (should be u64) but since Rust doesn't support negative durations we should be OK
        buf.putLong(value.seconds)
        // Type mismatch (should be u32) but since values will always be between 0 and 999,999,999 it should be OK
        buf.putInt(value.nano)
    }
}


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

// The base class for all UniFFI Object types.
//
// This class provides core operations for working with the Rust `Arc<T>` pointer to
// the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// the Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each `FFIObject` instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an `FFIObject` is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an `FFIObject` instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so will
//     leak the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each `FFIObject` an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// In the future we may be able to replace some of this with automatic finalization logic, such as using
// the new "Cleaner" functionaility in Java 9. The above scheme has been designed to work even if `destroy` is
// invoked by garbage-collection machinery rather than by calling code (which by the way, it's apparently also
// possible for the JVM to finalize an object while there is an in-flight call to one of its methods [1],
// so there would still be some complexity here).
//
// Sigh...all of this for want of a robust finalization mechanism.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//
abstract class FFIObject(
    protected val pointer: Pointer
): Disposable, AutoCloseable {

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    open protected fun freeRustArcPtr() {
        // To be overridden in subclasses.
    }

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.pointer)
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }
}

public interface LightningNodeInterface {
    
    fun `getNodeInfo`(): NodeInfo
    
    @Throws(LnException::class)
    fun `queryLspFee`(): LspFee
    
    @Throws(LnException::class)
    fun `calculateLspFee`(`amountMsat`: ULong): ULong
    
    @Throws(LnException::class)
    fun `createInvoice`(`amountMsat`: ULong, `description`: String, `metadata`: String): InvoiceDetails
    
    @Throws(LnException::class)
    fun `decodeInvoice`(`invoice`: String): InvoiceDetails
    
    @Throws(LnException::class)
    fun `payInvoice`(`invoice`: String, `metadata`: String)
    
    @Throws(LnException::class)
    fun `getLatestPayments`(`numberOfPayments`: UInt): List<Payment>
    
    @Throws(LnException::class)
    fun `getPayment`(`hash`: String): Payment
    
    fun `foreground`()
    
    fun `background`()
    
    @Throws(LnException::class)
    fun `listCurrencyCodes`(): List<String>
    
    @Throws(LnException::class)
    fun `getExchangeRates`(): ExchangeRates
    
    fun `changeFiatCurrency`(`fiatCurrency`: String)
    
    fun `changeTimezoneConfig`(`timezoneConfig`: TzConfig)
    
}

class LightningNode(
    pointer: Pointer
) : FFIObject(pointer), LightningNodeInterface {
    constructor(`config`: Config, `eventsCallback`: EventsCallback) :
        this(
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_new(FfiConverterTypeConfig.lower(`config`), FfiConverterTypeEventsCallback.lower(`eventsCallback`), _status)
})

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_lipalightninglib_7771_LightningNode_object_free(this.pointer, status)
        }
    }

    override fun `getNodeInfo`(): NodeInfo =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_get_node_info(it,  _status)
}
        }.let {
            FfiConverterTypeNodeInfo.lift(it)
        }
    
    @Throws(LnException::class)override fun `queryLspFee`(): LspFee =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_query_lsp_fee(it,  _status)
}
        }.let {
            FfiConverterTypeLspFee.lift(it)
        }
    
    @Throws(LnException::class)override fun `calculateLspFee`(`amountMsat`: ULong): ULong =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_calculate_lsp_fee(it, FfiConverterULong.lower(`amountMsat`),  _status)
}
        }.let {
            FfiConverterULong.lift(it)
        }
    
    @Throws(LnException::class)override fun `createInvoice`(`amountMsat`: ULong, `description`: String, `metadata`: String): InvoiceDetails =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_create_invoice(it, FfiConverterULong.lower(`amountMsat`), FfiConverterString.lower(`description`), FfiConverterString.lower(`metadata`),  _status)
}
        }.let {
            FfiConverterTypeInvoiceDetails.lift(it)
        }
    
    @Throws(LnException::class)override fun `decodeInvoice`(`invoice`: String): InvoiceDetails =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_decode_invoice(it, FfiConverterString.lower(`invoice`),  _status)
}
        }.let {
            FfiConverterTypeInvoiceDetails.lift(it)
        }
    
    @Throws(LnException::class)override fun `payInvoice`(`invoice`: String, `metadata`: String) =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_pay_invoice(it, FfiConverterString.lower(`invoice`), FfiConverterString.lower(`metadata`),  _status)
}
        }
    
    
    @Throws(LnException::class)override fun `getLatestPayments`(`numberOfPayments`: UInt): List<Payment> =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_get_latest_payments(it, FfiConverterUInt.lower(`numberOfPayments`),  _status)
}
        }.let {
            FfiConverterSequenceTypePayment.lift(it)
        }
    
    @Throws(LnException::class)override fun `getPayment`(`hash`: String): Payment =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_get_payment(it, FfiConverterString.lower(`hash`),  _status)
}
        }.let {
            FfiConverterTypePayment.lift(it)
        }
    override fun `foreground`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_foreground(it,  _status)
}
        }
    
    override fun `background`() =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_background(it,  _status)
}
        }
    
    
    @Throws(LnException::class)override fun `listCurrencyCodes`(): List<String> =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_list_currency_codes(it,  _status)
}
        }.let {
            FfiConverterSequenceString.lift(it)
        }
    
    @Throws(LnException::class)override fun `getExchangeRates`(): ExchangeRates =
        callWithPointer {
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_get_exchange_rates(it,  _status)
}
        }.let {
            FfiConverterTypeExchangeRates.lift(it)
        }
    override fun `changeFiatCurrency`(`fiatCurrency`: String) =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_change_fiat_currency(it, FfiConverterString.lower(`fiatCurrency`),  _status)
}
        }
    
    override fun `changeTimezoneConfig`(`timezoneConfig`: TzConfig) =
        callWithPointer {
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_LightningNode_change_timezone_config(it, FfiConverterTypeTzConfig.lower(`timezoneConfig`),  _status)
}
        }
    
    

    
}

public object FfiConverterTypeLightningNode: FfiConverter<LightningNode, Pointer> {
    override fun lower(value: LightningNode): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): LightningNode {
        return LightningNode(value)
    }

    override fun read(buf: ByteBuffer): LightningNode {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: LightningNode) = 8

    override fun write(value: LightningNode, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




data class ChannelsInfo (
    var `numChannels`: UShort, 
    var `numUsableChannels`: UShort, 
    var `localBalanceMsat`: ULong, 
    var `inboundCapacityMsat`: ULong, 
    var `outboundCapacityMsat`: ULong
) {
    
}

public object FfiConverterTypeChannelsInfo: FfiConverterRustBuffer<ChannelsInfo> {
    override fun read(buf: ByteBuffer): ChannelsInfo {
        return ChannelsInfo(
            FfiConverterUShort.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: ChannelsInfo) = (
            FfiConverterUShort.allocationSize(value.`numChannels`) +
            FfiConverterUShort.allocationSize(value.`numUsableChannels`) +
            FfiConverterULong.allocationSize(value.`localBalanceMsat`) +
            FfiConverterULong.allocationSize(value.`inboundCapacityMsat`) +
            FfiConverterULong.allocationSize(value.`outboundCapacityMsat`)
    )

    override fun write(value: ChannelsInfo, buf: ByteBuffer) {
            FfiConverterUShort.write(value.`numChannels`, buf)
            FfiConverterUShort.write(value.`numUsableChannels`, buf)
            FfiConverterULong.write(value.`localBalanceMsat`, buf)
            FfiConverterULong.write(value.`inboundCapacityMsat`, buf)
            FfiConverterULong.write(value.`outboundCapacityMsat`, buf)
    }
}




data class Config (
    var `network`: Network, 
    var `seed`: List<UByte>, 
    var `fiatCurrency`: String, 
    var `esploraApiUrl`: String, 
    var `rgsUrl`: String, 
    var `lspUrl`: String, 
    var `lspToken`: String, 
    var `localPersistencePath`: String, 
    var `timezoneConfig`: TzConfig, 
    var `graphqlUrl`: String, 
    var `backendHealthUrl`: String
) {
    
}

public object FfiConverterTypeConfig: FfiConverterRustBuffer<Config> {
    override fun read(buf: ByteBuffer): Config {
        return Config(
            FfiConverterTypeNetwork.read(buf),
            FfiConverterSequenceUByte.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeTzConfig.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Config) = (
            FfiConverterTypeNetwork.allocationSize(value.`network`) +
            FfiConverterSequenceUByte.allocationSize(value.`seed`) +
            FfiConverterString.allocationSize(value.`fiatCurrency`) +
            FfiConverterString.allocationSize(value.`esploraApiUrl`) +
            FfiConverterString.allocationSize(value.`rgsUrl`) +
            FfiConverterString.allocationSize(value.`lspUrl`) +
            FfiConverterString.allocationSize(value.`lspToken`) +
            FfiConverterString.allocationSize(value.`localPersistencePath`) +
            FfiConverterTypeTzConfig.allocationSize(value.`timezoneConfig`) +
            FfiConverterString.allocationSize(value.`graphqlUrl`) +
            FfiConverterString.allocationSize(value.`backendHealthUrl`)
    )

    override fun write(value: Config, buf: ByteBuffer) {
            FfiConverterTypeNetwork.write(value.`network`, buf)
            FfiConverterSequenceUByte.write(value.`seed`, buf)
            FfiConverterString.write(value.`fiatCurrency`, buf)
            FfiConverterString.write(value.`esploraApiUrl`, buf)
            FfiConverterString.write(value.`rgsUrl`, buf)
            FfiConverterString.write(value.`lspUrl`, buf)
            FfiConverterString.write(value.`lspToken`, buf)
            FfiConverterString.write(value.`localPersistencePath`, buf)
            FfiConverterTypeTzConfig.write(value.`timezoneConfig`, buf)
            FfiConverterString.write(value.`graphqlUrl`, buf)
            FfiConverterString.write(value.`backendHealthUrl`, buf)
    }
}




data class ExchangeRates (
    var `currencyCode`: String, 
    var `rate`: UInt, 
    var `usdRate`: UInt
) {
    
}

public object FfiConverterTypeExchangeRates: FfiConverterRustBuffer<ExchangeRates> {
    override fun read(buf: ByteBuffer): ExchangeRates {
        return ExchangeRates(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ExchangeRates) = (
            FfiConverterString.allocationSize(value.`currencyCode`) +
            FfiConverterUInt.allocationSize(value.`rate`) +
            FfiConverterUInt.allocationSize(value.`usdRate`)
    )

    override fun write(value: ExchangeRates, buf: ByteBuffer) {
            FfiConverterString.write(value.`currencyCode`, buf)
            FfiConverterUInt.write(value.`rate`, buf)
            FfiConverterUInt.write(value.`usdRate`, buf)
    }
}




data class FiatValues (
    var `fiat`: String, 
    var `amount`: ULong, 
    var `amountUsd`: ULong
) {
    
}

public object FfiConverterTypeFiatValues: FfiConverterRustBuffer<FiatValues> {
    override fun read(buf: ByteBuffer): FiatValues {
        return FiatValues(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: FiatValues) = (
            FfiConverterString.allocationSize(value.`fiat`) +
            FfiConverterULong.allocationSize(value.`amount`) +
            FfiConverterULong.allocationSize(value.`amountUsd`)
    )

    override fun write(value: FiatValues, buf: ByteBuffer) {
            FfiConverterString.write(value.`fiat`, buf)
            FfiConverterULong.write(value.`amount`, buf)
            FfiConverterULong.write(value.`amountUsd`, buf)
    }
}




data class InvoiceDetails (
    var `invoice`: String, 
    var `amountMsat`: ULong?, 
    var `description`: String, 
    var `paymentHash`: String, 
    var `payeePubKey`: String, 
    var `invoiceTimestamp`: java.time.Instant, 
    var `expiryInterval`: java.time.Duration
) {
    
}

public object FfiConverterTypeInvoiceDetails: FfiConverterRustBuffer<InvoiceDetails> {
    override fun read(buf: ByteBuffer): InvoiceDetails {
        return InvoiceDetails(
            FfiConverterString.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTimestamp.read(buf),
            FfiConverterDuration.read(buf),
        )
    }

    override fun allocationSize(value: InvoiceDetails) = (
            FfiConverterString.allocationSize(value.`invoice`) +
            FfiConverterOptionalULong.allocationSize(value.`amountMsat`) +
            FfiConverterString.allocationSize(value.`description`) +
            FfiConverterString.allocationSize(value.`paymentHash`) +
            FfiConverterString.allocationSize(value.`payeePubKey`) +
            FfiConverterTimestamp.allocationSize(value.`invoiceTimestamp`) +
            FfiConverterDuration.allocationSize(value.`expiryInterval`)
    )

    override fun write(value: InvoiceDetails, buf: ByteBuffer) {
            FfiConverterString.write(value.`invoice`, buf)
            FfiConverterOptionalULong.write(value.`amountMsat`, buf)
            FfiConverterString.write(value.`description`, buf)
            FfiConverterString.write(value.`paymentHash`, buf)
            FfiConverterString.write(value.`payeePubKey`, buf)
            FfiConverterTimestamp.write(value.`invoiceTimestamp`, buf)
            FfiConverterDuration.write(value.`expiryInterval`, buf)
    }
}




data class LspFee (
    var `channelMinimumFeeMsat`: ULong, 
    var `channelFeePermyriad`: ULong
) {
    
}

public object FfiConverterTypeLspFee: FfiConverterRustBuffer<LspFee> {
    override fun read(buf: ByteBuffer): LspFee {
        return LspFee(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: LspFee) = (
            FfiConverterULong.allocationSize(value.`channelMinimumFeeMsat`) +
            FfiConverterULong.allocationSize(value.`channelFeePermyriad`)
    )

    override fun write(value: LspFee, buf: ByteBuffer) {
            FfiConverterULong.write(value.`channelMinimumFeeMsat`, buf)
            FfiConverterULong.write(value.`channelFeePermyriad`, buf)
    }
}




data class NodeInfo (
    var `nodePubkey`: List<UByte>, 
    var `numPeers`: UShort, 
    var `channelsInfo`: ChannelsInfo
) {
    
}

public object FfiConverterTypeNodeInfo: FfiConverterRustBuffer<NodeInfo> {
    override fun read(buf: ByteBuffer): NodeInfo {
        return NodeInfo(
            FfiConverterSequenceUByte.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterTypeChannelsInfo.read(buf),
        )
    }

    override fun allocationSize(value: NodeInfo) = (
            FfiConverterSequenceUByte.allocationSize(value.`nodePubkey`) +
            FfiConverterUShort.allocationSize(value.`numPeers`) +
            FfiConverterTypeChannelsInfo.allocationSize(value.`channelsInfo`)
    )

    override fun write(value: NodeInfo, buf: ByteBuffer) {
            FfiConverterSequenceUByte.write(value.`nodePubkey`, buf)
            FfiConverterUShort.write(value.`numPeers`, buf)
            FfiConverterTypeChannelsInfo.write(value.`channelsInfo`, buf)
    }
}




data class Payment (
    var `paymentType`: PaymentType, 
    var `paymentState`: PaymentState, 
    var `hash`: String, 
    var `amountMsat`: ULong, 
    var `invoice`: String, 
    var `createdAt`: TzTime, 
    var `latestStateChangeAt`: TzTime, 
    var `description`: String, 
    var `preimage`: String?, 
    var `networkFeesMsat`: ULong?, 
    var `lspFeesMsat`: ULong?, 
    var `fiatValues`: FiatValues?, 
    var `metadata`: String
) {
    
}

public object FfiConverterTypePayment: FfiConverterRustBuffer<Payment> {
    override fun read(buf: ByteBuffer): Payment {
        return Payment(
            FfiConverterTypePaymentType.read(buf),
            FfiConverterTypePaymentState.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeTzTime.read(buf),
            FfiConverterTypeTzTime.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterOptionalTypeFiatValues.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Payment) = (
            FfiConverterTypePaymentType.allocationSize(value.`paymentType`) +
            FfiConverterTypePaymentState.allocationSize(value.`paymentState`) +
            FfiConverterString.allocationSize(value.`hash`) +
            FfiConverterULong.allocationSize(value.`amountMsat`) +
            FfiConverterString.allocationSize(value.`invoice`) +
            FfiConverterTypeTzTime.allocationSize(value.`createdAt`) +
            FfiConverterTypeTzTime.allocationSize(value.`latestStateChangeAt`) +
            FfiConverterString.allocationSize(value.`description`) +
            FfiConverterOptionalString.allocationSize(value.`preimage`) +
            FfiConverterOptionalULong.allocationSize(value.`networkFeesMsat`) +
            FfiConverterOptionalULong.allocationSize(value.`lspFeesMsat`) +
            FfiConverterOptionalTypeFiatValues.allocationSize(value.`fiatValues`) +
            FfiConverterString.allocationSize(value.`metadata`)
    )

    override fun write(value: Payment, buf: ByteBuffer) {
            FfiConverterTypePaymentType.write(value.`paymentType`, buf)
            FfiConverterTypePaymentState.write(value.`paymentState`, buf)
            FfiConverterString.write(value.`hash`, buf)
            FfiConverterULong.write(value.`amountMsat`, buf)
            FfiConverterString.write(value.`invoice`, buf)
            FfiConverterTypeTzTime.write(value.`createdAt`, buf)
            FfiConverterTypeTzTime.write(value.`latestStateChangeAt`, buf)
            FfiConverterString.write(value.`description`, buf)
            FfiConverterOptionalString.write(value.`preimage`, buf)
            FfiConverterOptionalULong.write(value.`networkFeesMsat`, buf)
            FfiConverterOptionalULong.write(value.`lspFeesMsat`, buf)
            FfiConverterOptionalTypeFiatValues.write(value.`fiatValues`, buf)
            FfiConverterString.write(value.`metadata`, buf)
    }
}




data class Secret (
    var `mnemonic`: List<String>, 
    var `passphrase`: String, 
    var `seed`: List<UByte>
) {
    
}

public object FfiConverterTypeSecret: FfiConverterRustBuffer<Secret> {
    override fun read(buf: ByteBuffer): Secret {
        return Secret(
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceUByte.read(buf),
        )
    }

    override fun allocationSize(value: Secret) = (
            FfiConverterSequenceString.allocationSize(value.`mnemonic`) +
            FfiConverterString.allocationSize(value.`passphrase`) +
            FfiConverterSequenceUByte.allocationSize(value.`seed`)
    )

    override fun write(value: Secret, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`mnemonic`, buf)
            FfiConverterString.write(value.`passphrase`, buf)
            FfiConverterSequenceUByte.write(value.`seed`, buf)
    }
}




data class TzConfig (
    var `timezoneId`: String, 
    var `timezoneUtcOffsetSecs`: Int
) {
    
}

public object FfiConverterTypeTzConfig: FfiConverterRustBuffer<TzConfig> {
    override fun read(buf: ByteBuffer): TzConfig {
        return TzConfig(
            FfiConverterString.read(buf),
            FfiConverterInt.read(buf),
        )
    }

    override fun allocationSize(value: TzConfig) = (
            FfiConverterString.allocationSize(value.`timezoneId`) +
            FfiConverterInt.allocationSize(value.`timezoneUtcOffsetSecs`)
    )

    override fun write(value: TzConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`timezoneId`, buf)
            FfiConverterInt.write(value.`timezoneUtcOffsetSecs`, buf)
    }
}




data class TzTime (
    var `timestamp`: java.time.Instant, 
    var `timezoneId`: String, 
    var `timezoneUtcOffsetSecs`: Int
) {
    
}

public object FfiConverterTypeTzTime: FfiConverterRustBuffer<TzTime> {
    override fun read(buf: ByteBuffer): TzTime {
        return TzTime(
            FfiConverterTimestamp.read(buf),
            FfiConverterString.read(buf),
            FfiConverterInt.read(buf),
        )
    }

    override fun allocationSize(value: TzTime) = (
            FfiConverterTimestamp.allocationSize(value.`timestamp`) +
            FfiConverterString.allocationSize(value.`timezoneId`) +
            FfiConverterInt.allocationSize(value.`timezoneUtcOffsetSecs`)
    )

    override fun write(value: TzTime, buf: ByteBuffer) {
            FfiConverterTimestamp.write(value.`timestamp`, buf)
            FfiConverterString.write(value.`timezoneId`, buf)
            FfiConverterInt.write(value.`timezoneUtcOffsetSecs`, buf)
    }
}




enum class LogLevel {
    ERROR,WARN,INFO,DEBUG,TRACE;
}

public object FfiConverterTypeLogLevel: FfiConverterRustBuffer<LogLevel> {
    override fun read(buf: ByteBuffer) = try {
        LogLevel.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: LogLevel) = 4

    override fun write(value: LogLevel, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Network {
    BITCOIN,TESTNET,SIGNET,REGTEST;
}

public object FfiConverterTypeNetwork: FfiConverterRustBuffer<Network> {
    override fun read(buf: ByteBuffer) = try {
        Network.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Network) = 4

    override fun write(value: Network, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class PaymentState {
    CREATED,SUCCEEDED,FAILED;
}

public object FfiConverterTypePaymentState: FfiConverterRustBuffer<PaymentState> {
    override fun read(buf: ByteBuffer) = try {
        PaymentState.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PaymentState) = 4

    override fun write(value: PaymentState, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class PaymentType {
    RECEIVING,SENDING;
}

public object FfiConverterTypePaymentType: FfiConverterRustBuffer<PaymentType> {
    override fun read(buf: ByteBuffer) = try {
        PaymentType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PaymentType) = 4

    override fun write(value: PaymentType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class RuntimeErrorCode {
    ESPLORA_SERVICE_UNAVAILABLE,EXCHANGE_RATE_PROVIDER_UNAVAILABLE,LSP_SERVICE_UNAVAILABLE,REMOTE_STORAGE_ERROR,RGS_SERVICE_UNAVAILABLE,RGS_UPDATE_ERROR,OBJECT_NOT_FOUND,ALREADY_USED_INVOICE,NO_ROUTE_FOUND,SEND_FAILURE,GENERIC_ERROR;
}

public object FfiConverterTypeRuntimeErrorCode: FfiConverterRustBuffer<RuntimeErrorCode> {
    override fun read(buf: ByteBuffer) = try {
        RuntimeErrorCode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: RuntimeErrorCode) = 4

    override fun write(value: RuntimeErrorCode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class LnException: Exception() {
    // Each variant is a nested class
    
    class InvalidInput(
        val `msg`: String
        ) : LnException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class RuntimeException(
        val `code`: RuntimeErrorCode, 
        val `msg`: String
        ) : LnException() {
        override val message
            get() = "code=${ `code` }, msg=${ `msg` }"
    }
    
    class PermanentFailure(
        val `msg`: String
        ) : LnException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : CallStatusErrorHandler<LnException> {
        override fun lift(error_buf: RustBuffer.ByValue): LnException = FfiConverterTypeLnError.lift(error_buf)
    }

    
}

public object FfiConverterTypeLnError : FfiConverterRustBuffer<LnException> {
    override fun read(buf: ByteBuffer): LnException {
        

        return when(buf.getInt()) {
            1 -> LnException.InvalidInput(
                FfiConverterString.read(buf),
                )
            2 -> LnException.RuntimeException(
                FfiConverterTypeRuntimeErrorCode.read(buf),
                FfiConverterString.read(buf),
                )
            3 -> LnException.PermanentFailure(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: LnException): Int {
        return when(value) {
            is LnException.InvalidInput -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is LnException.RuntimeException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterTypeRuntimeErrorCode.allocationSize(value.`code`)
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is LnException.PermanentFailure -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: LnException, buf: ByteBuffer) {
        when(value) {
            is LnException.InvalidInput -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is LnException.RuntimeException -> {
                buf.putInt(2)
                FfiConverterTypeRuntimeErrorCode.write(value.`code`, buf)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is LnException.PermanentFailure -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




internal typealias Handle = Long
internal class ConcurrentHandleMap<T>(
    private val leftMap: MutableMap<Handle, T> = mutableMapOf(),
    private val rightMap: MutableMap<T, Handle> = mutableMapOf()
) {
    private val lock = java.util.concurrent.locks.ReentrantLock()
    private val currentHandle = AtomicLong(0L)
    private val stride = 1L

    fun insert(obj: T): Handle =
        lock.withLock {
            rightMap[obj] ?:
                currentHandle.getAndAdd(stride)
                    .also { handle ->
                        leftMap[handle] = obj
                        rightMap[obj] = handle
                    }
            }

    fun get(handle: Handle) = lock.withLock {
        leftMap[handle]
    }

    fun delete(handle: Handle) {
        this.remove(handle)
    }

    fun remove(handle: Handle): T? =
        lock.withLock {
            leftMap.remove(handle)?.let { obj ->
                rightMap.remove(obj)
                obj
            }
        }
}

interface ForeignCallback : com.sun.jna.Callback {
    public fun invoke(handle: Handle, method: Int, args: RustBuffer.ByValue, outBuf: RustBufferByReference): Int
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0

public abstract class FfiConverterCallbackInterface<CallbackInterface>(
    protected val foreignCallback: ForeignCallback
): FfiConverter<CallbackInterface, Handle> {
    private val handleMap = ConcurrentHandleMap<CallbackInterface>()

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal abstract fun register(lib: _UniFFILib)

    fun drop(handle: Handle): RustBuffer.ByValue {
        return handleMap.remove(handle).let { RustBuffer.ByValue() }
    }

    override fun lift(value: Handle): CallbackInterface {
        return handleMap.get(value) ?: throw InternalException("No callback in handlemap; this is a Uniffi bug")
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) =
        handleMap.insert(value).also {
            assert(handleMap.get(it) === value) { "Handle map is not returning the object we just placed there. This is a bug in the HandleMap." }
        }

    override fun allocationSize(value: CallbackInterface) = 8

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

// Declaration and FfiConverters for EventsCallback Callback Interface

public interface EventsCallback {
    fun `paymentReceived`(`paymentHash`: String, `amountMsat`: ULong)
    fun `paymentSent`(`paymentHash`: String, `paymentPreimage`: String, `feePaidMsat`: ULong)
    fun `paymentFailed`(`paymentHash`: String)
    fun `channelClosed`(`channelId`: String, `reason`: String)
    
}

// The ForeignCallback that is passed to Rust.
internal class ForeignCallbackTypeEventsCallback : ForeignCallback {
    @Suppress("TooGenericExceptionCaught")
    override fun invoke(handle: Handle, method: Int, args: RustBuffer.ByValue, outBuf: RustBufferByReference): Int {
        val cb = FfiConverterTypeEventsCallback.lift(handle)
        return when (method) {
            IDX_CALLBACK_FREE -> {
                FfiConverterTypeEventsCallback.drop(handle)
                // No return value.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                0
            }
            1 -> {
                // Call the method, write to outBuf and return a status code
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs` for info
                try {
                    val buffer = this.`invokePaymentReceived`(cb, args)
                    // Success
                    outBuf.setValue(buffer)
                    1
                } catch (e: Throwable) {
                    // Unexpected error
                    try {
                        // Try to serialize the error into a string
                        outBuf.setValue(FfiConverterString.lower(e.toString()))
                    } catch (e: Throwable) {
                        // If that fails, then it's time to give up and just return
                    }
                    -1
                }
            }
            2 -> {
                // Call the method, write to outBuf and return a status code
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs` for info
                try {
                    val buffer = this.`invokePaymentSent`(cb, args)
                    // Success
                    outBuf.setValue(buffer)
                    1
                } catch (e: Throwable) {
                    // Unexpected error
                    try {
                        // Try to serialize the error into a string
                        outBuf.setValue(FfiConverterString.lower(e.toString()))
                    } catch (e: Throwable) {
                        // If that fails, then it's time to give up and just return
                    }
                    -1
                }
            }
            3 -> {
                // Call the method, write to outBuf and return a status code
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs` for info
                try {
                    val buffer = this.`invokePaymentFailed`(cb, args)
                    // Success
                    outBuf.setValue(buffer)
                    1
                } catch (e: Throwable) {
                    // Unexpected error
                    try {
                        // Try to serialize the error into a string
                        outBuf.setValue(FfiConverterString.lower(e.toString()))
                    } catch (e: Throwable) {
                        // If that fails, then it's time to give up and just return
                    }
                    -1
                }
            }
            4 -> {
                // Call the method, write to outBuf and return a status code
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs` for info
                try {
                    val buffer = this.`invokeChannelClosed`(cb, args)
                    // Success
                    outBuf.setValue(buffer)
                    1
                } catch (e: Throwable) {
                    // Unexpected error
                    try {
                        // Try to serialize the error into a string
                        outBuf.setValue(FfiConverterString.lower(e.toString()))
                    } catch (e: Throwable) {
                        // If that fails, then it's time to give up and just return
                    }
                    -1
                }
            }
            
            else -> {
                // An unexpected error happened.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                try {
                    // Try to serialize the error into a string
                    outBuf.setValue(FfiConverterString.lower("Invalid Callback index"))
                } catch (e: Throwable) {
                    // If that fails, then it's time to give up and just return
                }
                -1
            }
        }
    }

    
    private fun `invokePaymentReceived`(kotlinCallbackInterface: EventsCallback, args: RustBuffer.ByValue): RustBuffer.ByValue =
        try {
            val buf = args.asByteBuffer() ?: throw InternalException("No ByteBuffer in RustBuffer; this is a Uniffi bug")
            kotlinCallbackInterface.`paymentReceived`(
                    FfiConverterString.read(buf), 
                    FfiConverterULong.read(buf)
                    )
            .let { RustBuffer.ByValue() }
                // TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351
        } finally {
            RustBuffer.free(args)
        }

    
    private fun `invokePaymentSent`(kotlinCallbackInterface: EventsCallback, args: RustBuffer.ByValue): RustBuffer.ByValue =
        try {
            val buf = args.asByteBuffer() ?: throw InternalException("No ByteBuffer in RustBuffer; this is a Uniffi bug")
            kotlinCallbackInterface.`paymentSent`(
                    FfiConverterString.read(buf), 
                    FfiConverterString.read(buf), 
                    FfiConverterULong.read(buf)
                    )
            .let { RustBuffer.ByValue() }
                // TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351
        } finally {
            RustBuffer.free(args)
        }

    
    private fun `invokePaymentFailed`(kotlinCallbackInterface: EventsCallback, args: RustBuffer.ByValue): RustBuffer.ByValue =
        try {
            val buf = args.asByteBuffer() ?: throw InternalException("No ByteBuffer in RustBuffer; this is a Uniffi bug")
            kotlinCallbackInterface.`paymentFailed`(
                    FfiConverterString.read(buf)
                    )
            .let { RustBuffer.ByValue() }
                // TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351
        } finally {
            RustBuffer.free(args)
        }

    
    private fun `invokeChannelClosed`(kotlinCallbackInterface: EventsCallback, args: RustBuffer.ByValue): RustBuffer.ByValue =
        try {
            val buf = args.asByteBuffer() ?: throw InternalException("No ByteBuffer in RustBuffer; this is a Uniffi bug")
            kotlinCallbackInterface.`channelClosed`(
                    FfiConverterString.read(buf), 
                    FfiConverterString.read(buf)
                    )
            .let { RustBuffer.ByValue() }
                // TODO catch errors and report them back to Rust.
                // https://github.com/mozilla/uniffi-rs/issues/351
        } finally {
            RustBuffer.free(args)
        }

    
}

// The ffiConverter which transforms the Callbacks in to Handles to pass to Rust.
public object FfiConverterTypeEventsCallback: FfiConverterCallbackInterface<EventsCallback>(
    foreignCallback = ForeignCallbackTypeEventsCallback()
) {
    override fun register(lib: _UniFFILib) {
        rustCall() { status ->
            lib.ffi_lipalightninglib_7771_EventsCallback_init_callback(this.foreignCallback, status)
        }
    }
}




public object FfiConverterOptionalULong: FfiConverterRustBuffer<ULong?> {
    override fun read(buf: ByteBuffer): ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: ULong?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




public object FfiConverterOptionalTypeFiatValues: FfiConverterRustBuffer<FiatValues?> {
    override fun read(buf: ByteBuffer): FiatValues? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFiatValues.read(buf)
    }

    override fun allocationSize(value: FiatValues?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypeFiatValues.allocationSize(value)
        }
    }

    override fun write(value: FiatValues?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFiatValues.write(value, buf)
        }
    }
}




public object FfiConverterSequenceUByte: FfiConverterRustBuffer<List<UByte>> {
    override fun read(buf: ByteBuffer): List<UByte> {
        val len = buf.getInt()
        return List<UByte>(len) {
            FfiConverterUByte.read(buf)
        }
    }

    override fun allocationSize(value: List<UByte>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterUByte.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<UByte>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterUByte.write(it, buf)
        }
    }
}




public object FfiConverterSequenceString: FfiConverterRustBuffer<List<String>> {
    override fun read(buf: ByteBuffer): List<String> {
        val len = buf.getInt()
        return List<String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<String>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypePayment: FfiConverterRustBuffer<List<Payment>> {
    override fun read(buf: ByteBuffer): List<Payment> {
        val len = buf.getInt()
        return List<Payment>(len) {
            FfiConverterTypePayment.read(buf)
        }
    }

    override fun allocationSize(value: List<Payment>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypePayment.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Payment>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypePayment.write(it, buf)
        }
    }
}

fun `initNativeLoggerOnce`(`minLevel`: LogLevel) =
    
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_init_native_logger_once(FfiConverterTypeLogLevel.lower(`minLevel`), _status)
}

@Throws(LnException::class)

fun `generateSecret`(`passphrase`: String): Secret {
    return FfiConverterTypeSecret.lift(
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_generate_secret(FfiConverterString.lower(`passphrase`), _status)
})
}


@Throws(LnException::class)

fun `mnemonicToSecret`(`mnemonicString`: List<String>, `passphrase`: String): Secret {
    return FfiConverterTypeSecret.lift(
    rustCallWithError(LnException) { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_mnemonic_to_secret(FfiConverterSequenceString.lower(`mnemonicString`), FfiConverterString.lower(`passphrase`), _status)
})
}



fun `wordsByPrefix`(`prefix`: String): List<String> {
    return FfiConverterSequenceString.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.lipalightninglib_7771_words_by_prefix(FfiConverterString.lower(`prefix`), _status)
})
}




